os:
  - Visual Studio 2017
  - Visual Studio 2015

configuration:
  - Debug
  - Release

environment:
  CTEST_OUTPUT_ON_FAILURE: 1

install:
  - vcpkg install protobuf
  - hg summary
  # ign-cmake
  - hg clone https://bitbucket.org/ignitionrobotics/ign-cmake
  - cd ign-cmake
  - hg up LiteralProject
  - md build
  - cd build
  - cmake ..
  - cmake --build . --target INSTALL
  - cd ../..
  # ign-math
  - hg clone https://bitbucket.org/ignitionrobotics/ign-math
  - cd ign-math
  - hg up CMakeRefactor_LiteralProject
  - md build
  - cd build
  - cmake ..
  - cmake --build . --target INSTALL
  - cd ../..
build_script:
  - md build
  - cd build
  - cmake ..
      -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake
      #-DCMAKE_CXX_FLAGS="-WX"
  - cmake --build . --config %CONFIGURATION%

after_build:
  - cmake --build . --config %CONFIGURATION% --target INSTALL
  
#test_script:
#  - cmake --build . --config %CONFIGURATION% --target RUN_TESTS
