os:
  - Visual Studio 2015
  - Visual Studio 2017

configuration:
  - Debug
  - Release

environment:
  CTEST_OUTPUT_ON_FAILURE: 1

install:
  - vcpkg install protobuf
  - appveyor PushArtifact c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake
  - hg summary
  # ign-cmake
  - hg clone https://bitbucket.org/ignitionrobotics/ign-cmake
  - cd ign-cmake
  - hg up default
  - md build
  - cd build
  - cmake ..
  - cmake --build . --target INSTALL
  - cd ../..
  # ign-math
  - hg clone https://bitbucket.org/ignitionrobotics/ign-math
  - cd ign-math
  - hg up CMakeRefactor-default
  - md build
  - cd build
  - cmake ..
  - cmake --build . --target INSTALL
  - cd ../..
build_script:
  - md build
  - cd build
  - cmake ..
      -DCMAKE_CXX_FLAGS="-WX"
      -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake
  - cmake --build . --config %CONFIGURATION%

after_build:
  - cmake --build . --config %CONFIGURATION% --target INSTALL
  
test_script:
  - cmake --build . --config %CONFIGURATION% --target RUN_TESTS
