image: ubuntu:xenial

pipelines:
  default:
    - step:
        script:
          - echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable xenial main" > /etc/apt/sources.list.d/gazebo-stable.list
          - apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys D2486D2DD83DB69272AFE98867170598AF249743
          - apt-get update
          - apt-get -y install
            cmake build-essential lcov curl mercurial libprotobuf-dev protobuf-compiler libprotoc-dev
            libignition-cmake-dev
            libignition-math4-dev
            ruby
          # Ignition tools
          - hg clone http://bitbucket.org/ignitionrobotics/ign-tools -b default
          - cd ign-tools
          - mkdir build
          - cd build
          - cmake .. -DCMAKE_INSTALL_PREFIX=/usr
          - make -j4 install
          - cd ../..
          - ls /usr/bin
          - ls /usr/local/bin
          - ls /usr/share/ignition
          - cat /usr/share/ignition/msgs1.yaml
          # Ignition msgs
          - mkdir build
          - cd build
          - cmake .. -DCMAKE_BUILD_TYPE=coverage
          - make
          - make test ARGS="-V" CTEST_OUTPUT_ON_FAILURE=1
          - make coverage
          - bash <(curl -s https://codecov.io/bash)
          # code_check
          - cd ..
          - sh tools/code_check.sh
