image: ubuntu:xenial

pipelines:
  default:
    - step:
        script:
          - apt-get update
          - apt-get -y install cmake build-essential lcov curl mercurial libprotobuf-dev protobuf-compiler libprotoc-dev libignition-math3-dev
          - mkdir build
          - cd build
          - cmake .. -DCMAKE_BUILD_TYPE=coverage
          - make
          - make test
          - make coverage
          - bash <(curl -s https://codecov.io/bash)
